### ISSUE TITLE
.clang-format config file is ignored on macOS

### ISSUE THREAD

**Issue by bsergean** [pocc/pre-commit-hooks#4]
My .clang-format file isn't processed ... could it be a bug in pre-commit ?

This is the repo I'm using -> https://github.com/machinezone/IXWebSocket

Any clue ?

**Comment by pocc** [comment]
Please provide your `.pre-commit-config.yaml`. I checked master of that project and it doesn't have one.

**Comment by bsergean** [comment]
yaml file:

```
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/pocc/pre-commit-hooks
    rev: ''
    hooks:
    -   id: clang-format
```

Here is the error I'm getting actually ... maybe I'm using an incompatible clang-format version.

```
Check Yaml...............................................................Passed
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Failed
hookid: trailing-whitespace

Files were modified by this hook. Additional output:

Fixing .pre-commit-config.yaml

clang-format.............................................................Failed
hookid: clang-format

readlink: illegal option -- f
usage: readlink [-n] [file ...]
/Users/bsergeant/.cache/pre-commit/repo3a04cljy/hooks/clang-format: line 7: ./utils: No such file or directory
/Users/bsergeant/.cache/pre-commit/repo3a04cljy/hooks/clang-format: line 30: check_installed: command not found
/Users/bsergeant/.cache/pre-commit/repo3a04cljy/hooks/clang-format: line 32: diff_formatted: command not found
```

**Comment by bsergean** [comment]
Also I'm running this on macOS, where readlink does not seem to have a -f option.

**Comment by pocc** [comment]
It looks like a common solution to this is installing coreutils: http://biercoff.com/readlink-f-unrecognized-option-problem-solution-on-mac/

**Comment by zbeekman** [comment]
yes..... but shouldn't you provide cross-platform (or at least Unix-like compatible) hooks?

**Comment by zbeekman** [comment]
So there are a few problems here.

The first is that these hooks are all broken on *nix other than linux due to a non-robust locating of the utils functions. I have fixed that in #6.

The second problem is that you probably need the `-style=file` option passed in args. Something like this:

```
-   repo: https://github.com/pocc/pre-commit-hooks
    rev: ''
    hooks:
    -   id: clang-format
        args: [-style=file, -i, --fallback-style=none]
```

Finally, the testing framework seems a bit fragile. I fixed (in #6) an issue where newer clang-tidy produces an unexpected error for `err.cpp` from a new rule that was added.

But the problem remains that the test for OClint expectes and exactly matching version number, AND, the order of the errors it outputs may not be deterministic.

**Comment by guihao-liang** [comment]
Is it better to mention `readlink` behaves differently on macOS and Linux in README? It takes me some time to figure it out.

**Comment by TheButlah** [comment]
This hit me today - It would be good for this to work out of the box, without having to install `coreutils`

**Comment by pocc** [comment]
I agree it should work out of the box and have consistent behavior, which is why is why I am moving these bash hooks to python hooks.

On coreutils, I'm opinionated that it *should* be installed because I've banged my head against enough minor inconsistencies between BSD and GNU versions of tools like sed, grep, ps, ls, etc.
